name: App1 CI-CD

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    uses: spring-service/ci-templates/.github/workflows/docker-k8s-deploy.yml@main
    with:
      app_name: app1
      image_name: techie019/cardsys:app1v1
